# Generated by Django 4.2.3 on 2023-07-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_page_description_alter_page_keywords_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='UserData',
        ),
    ]
